services:
  nextjs:
    build:
      context: ../..
      dockerfile: devops/Dockerfile
      args:
        - DEPLOYMENT_ID=${DEPLOYMENT_ID}
        - NODE_ENV=${NODE_ENV}
        - CACHEBUST=${CACHEBUST}
    container_name: default-router
    restart: always
    environment:
      - NODE_ENV=${NODE_ENV}
      - NEXT_PUBLIC_API_BASE_URL=${BE_URL}
      - NEXTAUTH_SECRET=8ea28feed665d06fd12c8a1a35b90577293531b59c3e8b8316213c89b5e5d62c
      - NEXT_PUBLIC_API_PATH=api
      - NEXT_PUBLIC_API_VERSION=v1
      - NEXT_PUBLIC_CACHE_BUST=${CACHEBUST}
      - DEPLOYMENT_ID=${DEPLOYMENT_ID}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.default-router.rule=HostRegexp(`^(?!website-)(.+\\.)?constrix-nv\\.com$`)"
      - "traefik.http.routers.default-router.entrypoints=https"
      - "traefik.http.routers.default-router.tls.certresolver=letsencrypt"
      - "traefik.http.services.default-router.loadbalancer.server.port=3000"
      - "traefik.http.routers.default-router.priority=11"
    networks:
      - traefik_network

networks:
  traefik_network:
    external: true
